# Fail2Ban configuration file
#
# Regexp to detect access on public pages so we can add mitigation on IP making too much
# access to your a OnLi instance.

[Definition]

# To test, you can inject this example into log
# echo `date +'%Y-%m-%d %H:%M:%S'`" INFO    1.2.3.4    --- Access to GET /public/clicktodial/cidlookup.php" >> /mypath/documents/OnLi.log
#
# then
# fail2ban-client status web-OnLi-limitpublic
#
# To test rule file on a existing log file
# fail2ban-regex /mypath/documents/OnLi.log /etc/fail2ban/filter.d/web-OnLi-limitpublic.conf --print-all-matched

failregex = ^ [A-Z\s]+ <HOST>\s+--- Access to .*/public/
ignoreregex =
