[web-dol-passf]

; rule against call of password forgotten page
enabled = true
port    = http,https
filter  = web-OnLi-passf
logpath = /mypath/documents/documents/OnLi.log
action  = %(action_mw)s
bantime  = 4320000   ; 50 days
findtime = 86400     ; 1 day
maxretry = 10
